----Calculate the percentage contribution of each pizza type to total revenue.

SELECT PIZZA_TYPES.CATEGORY,
SUM(ORDER_DETAILS.QUANTITY*PIZZAS.PRICE) AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.CATEGORY
ORDER BY REVENUE DESC;


SELECT
    PIZZA_TYPES.CATEGORY,
    ROUND(
        (
            SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) /
            (
                SELECT SUM(OD.QUANTITY * P.PRICE)
                FROM ORDER_DETAILS AS OD
                JOIN PIZZAS AS P
                    ON OD.PIZZA_ID = P.PIZZA_ID
            )
        ) * 100,
        2
    ) AS REVENUE
FROM PIZZA_TYPES
JOIN PIZZAS
    ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDER_DETAILS
    ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.CATEGORY
ORDER BY REVENUE DESC;


-----Analyze the cumulative revenue generated over time.

SELECT ORDERS.date,
SUM(ORDER_DETAILS.quantity * PIZZAS.price) AS REVENUE
FROM ORDER_DETAILS JOIN PIZZAS
ON ORDER_DETAILS.pizza_id = PIZZAS.pizza_id
JOIN ORDERS
ON ORDERS.order_id = ORDER_DETAILS.order_id
GROUP BY ORDERS.date;


select date,
sum(revenue) over(order by date) as cum_revenue
from
(SELECT ORDERS.date,
SUM(ORDER_DETAILS.quantity * PIZZAS.price) AS REVENUE
FROM ORDER_DETAILS JOIN PIZZAS
ON ORDER_DETAILS.pizza_id = PIZZAS.pizza_id
JOIN ORDERS
ON ORDERS.order_id = ORDER_DETAILS.order_id
GROUP BY ORDERS.date) as sales;


-----Determine the top 3 most ordered pizza types based on revenue for each pizza category.

SELECT PIZZA_TYPES.category, PIZZA_TYPES.name,
SUM((ORDER_DETAILS.quantity) * PIZZAS.price) AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.pizza_type_id = PIZZAS.pizza_type_id
JOIN ORDER_DETAILS
ON ORDER_DETAILS.pizza_id = PIZZAS.pizza_id
GROUP BY PIZZA_TYPES.category, PIZZA_TYPES.NAME;

ALTER TABLE PIZZA_TYPES
ALTER COLUMN NAME VARCHAR(100);

ALTER TABLE PIZZA_TYPES
ALTER COLUMN CATEGORY VARCHAR(50);


SELECT CATEGORY, NAME, REVENUE,
RANK() OVER(PARTITION BY CATEGORY ORDER BY REVENUE DESC) AS RN
FROM
(SELECT PIZZA_TYPES.category, PIZZA_TYPES.name,
SUM((ORDER_DETAILS.quantity) * PIZZAS.price) AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.pizza_type_id = PIZZAS.pizza_type_id
JOIN ORDER_DETAILS
ON ORDER_DETAILS.pizza_id = PIZZAS.pizza_id
GROUP BY PIZZA_TYPES.category, PIZZA_TYPES.NAME) AS A;

SELECT NAME, REVENUE FROM
(SELECT CATEGORY, NAME, REVENUE,
RANK() OVER(PARTITION BY CATEGORY ORDER BY REVENUE DESC) AS RN
FROM
(SELECT PIZZA_TYPES.category, PIZZA_TYPES.name,
SUM((ORDER_DETAILS.quantity) * PIZZAS.price) AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.pizza_type_id = PIZZAS.pizza_type_id
JOIN ORDER_DETAILS
ON ORDER_DETAILS.pizza_id = PIZZAS.pizza_id
GROUP BY PIZZA_TYPES.category, PIZZA_TYPES.NAME) AS A) AS B
WHERE RN <=3;










































