CREATE DATABASE PIZZAHUT;

USE PIZZAHUT;

-----Retrieve the total number of orders placed.

SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS;


-----Calculate the total revenue generated from pizza sales.

SELECT 
    (O.QUANTITY * P.PRICE) AS TOTAL_SALES
FROM ORDER_DETAILS AS O
JOIN 
PIZZAS AS P
ON CAST(P.PIZZA_ID AS VARCHAR(20))
= CAST(O.PIZZA_ID AS VARCHAR(20));

SELECT
    (O.QUANTITY * P.PRICE) AS TOTAL_SALES
FROM ORDER_DETAILS  AS O
JOIN PIZZAS AS P
ON P.PIZZA_ID = O.PIZZA_ID;

SELECT
    SUM(O.QUANTITY * P.PRICE) AS TOTAL_SALES
FROM ORDER_DETAILS  AS O
JOIN PIZZAS AS P
ON CONVERT(VARCHAR(20), P.PIZZA_ID)
 = CONVERT(VARCHAR(20), O.PIZZA_ID);

SELECT
    ROUND(SUM(O.QUANTITY * P.PRICE),2) AS TOTAL_SALES
FROM ORDER_DETAILS  AS O
JOIN PIZZAS AS P
ON CONVERT(VARCHAR(20), P.PIZZA_ID)
 = CONVERT(VARCHAR(20), O.PIZZA_ID);


SP_HELP ORDER_DETAILS;

SP_HELP PIZZAS;

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='ORDER_DETAILS';

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='PIZZAS';

ALTER TABLE ORDER_DETAILS
ALTER COLUMN PIZZA_ID VARCHAR(20);

ALTER TABLE PIZZAS
ALTER COLUMN PIZZA_ID VARCHAR(20);



ALTER TABLE ORDER_DETAILS
ALTER COLUMN PIZZA_ID INT;

ALTER TABLE PIZZAS
ALTER COLUMN PIZZA_ID INT;


ON CONVERT(VARCHAR(20), P.PIZZA_ID)
 = CONVERT(VARCHAR(20), O.PIZZA_ID);


------Identify the highest-priced pizza.

SELECT P.NAME, S.PRICE
FROM PIZZA_TYPES AS P
JOIN PIZZAS AS S
ON P.PIZZA_TYPE_ID = S.PIZZA_TYPE_ID

SELECT * FROM PIZZAS;

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES;

SELECT TOP 1
       P.NAME, 
	   S.PRICE
FROM PIZZA_TYPES AS P
JOIN PIZZAS AS S
ON CAST(P.PIZZA_TYPE_ID AS VARCHAR(20))
= CAST(S.PIZZA_TYPE_ID AS VARCHAR(20))
ORDER BY S.PRICE DESC;


SP_HELP ORDER_DETAILS;

SP_HELP PIZZAS;

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='PIZZA_TYPES';

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='PIZZAS';


SELECT * FROM PIZZA_TYPES;

SELECT * FROM PIZZAS;



-----Identify the most common pizza size ordered.

SELECT * FROM ORDER_DETAILS

SELECT QUANTITY, COUNT(ORDER_DETAILS_ID)
FROM ORDER_DETAILS
GROUP BY QUANTITY;

SELECT * FROM PIZZAS

SELECT P.SIZE, COUNT(O.ORDER_DETAILS_ID) AS ORDER_COUNT 
FROM PIZZAS AS P 
JOIN ORDER_DETAILS AS O 
ON P.PIZZA_ID = O.PIZZA_ID 
GROUP BY P.SIZE
ORDER BY ORDER_COUNT DESC;

ALTER TABLE PIZZAS
ALTER COLUMN SIZE VARCHAR(10);


SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='PIZZAS';

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='ORDER_DETAILS';

------List the top 5 most ordered pizza 
------types along with their quantities.

SELECT 
    CAST(P.NAME AS VARCHAR(100)) AS PIZZA_NAME,
    CAST(O.QUANTITY AS INT) AS TOTAL_QUANTITY
FROM PIZZA_TYPES AS P
JOIN PIZZAS AS S
    ON CAST(P.pizza_type_id AS VARCHAR(10)) = CAST(S.pizza_type_id AS VARCHAR(10))
JOIN ORDER_DETAILS AS O
    ON CAST(O.pizza_id AS VARCHAR(10)) = CAST(S.pizza_id AS VARCHAR(10));

SELECT 
    CAST(P.NAME AS VARCHAR(100)) AS PIZZA_NAME,
    SUM(CAST(O.QUANTITY AS INT)) AS TOTAL_QUANTITY
FROM PIZZA_TYPES AS P
JOIN PIZZAS AS S
    ON CAST(P.pizza_type_id AS VARCHAR(10)) = CAST(S.pizza_type_id AS VARCHAR(10))
JOIN ORDER_DETAILS AS O
    ON CAST(O.pizza_id AS VARCHAR(10)) = CAST(S.pizza_id AS VARCHAR(10))
GROUP BY CAST(P.NAME AS VARCHAR(100));



SELECT TOP 5
    CAST(P.NAME AS VARCHAR(100)) AS PIZZA_NAME,
    SUM(CAST(O.QUANTITY AS INT)) AS TOTAL_QUANTITY
FROM PIZZA_TYPES AS P
JOIN PIZZAS AS S
    ON CAST(P.pizza_type_id AS VARCHAR(10)) = CAST(S.pizza_type_id AS VARCHAR(10))
JOIN ORDER_DETAILS AS O
    ON CAST(O.pizza_id AS VARCHAR(10)) = CAST(S.pizza_id AS VARCHAR(10))
GROUP BY CAST(P.NAME AS VARCHAR(100))
ORDER BY TOTAL_QUANTITY DESC;

 

SP_HELP PIZZA_TYPES;

SP_HELP PIZZAS;
  

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='PIZZAS';

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='PIZZA_TYPES';

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='ORDER_DETAILS';



